### ISSUE TITLE
Suggestion: Support for termite

### ISSUE THREAD

**Issue by theova** [AuditeMarlow/base16-manager#14]
Hello,

I enjoy your base16-manager very much! It's super easy to test other colorschemes with it!
Thank you very much!

For my personal needs, I had to extend the manger for termite.
Here is, what I'm doing:

Add function to `set_theme()`:
```
# ... 
 "khamer/base16-termite")

	set_termite "${package}" "${theme}"
	;;
# ...
```
And the new function itself:
```
set_termite() {
  local package=$1
  local theme=$2
  local file="${CONFIG_PATH}/${package}/themes/base16-${theme}.config"
  local termite_dir="${HOME}/.config/termite"
  local config="${termite_dir}/config"

  if ! file_exists ${file}; then
    err "Termite theme not found."
  else
    check_dir $termite_dir
    [[ -f "${config}.bac" ]] && rm "${config}.bac"
    [[ -f "${config}" ]] && cp ${config} "${config}.bac" || touch ${config}
    sed '/^\[colors\]$/,/^\[\w*\]$/{/^\[\w*\]$/!d}' ${config} | grep --invert-match '\[colors\]' > /tmp/termiterc
    cp /tmp/termiterc ${config}
    cat ${file} >> ${config}
  fi
}
```

The sed command may not be the most elegant, but I hadn't achieved the desired otherwise.

It would be cool, to see this code included in base16-manager :-)

**Comment by AuditeMarlow** [comment]
Hey there, thanks for being so excited about this project! I'd be more than happy to test and include your additions. Could you create a pull request for this? I'd be able to test this myself and merge it into the mainline.

**Comment by theova** [comment]
I created the pull request.
