### ISSUE TITLE
Feature request: Install new theme

### ISSUE THREAD

**Issue by roguh** [AuditeMarlow/base16-manager#19]
Hi! Thank you for this tool. I found it very helpful.

I'd like it if base16-manager could use a template's YAML and mustache files to generate any missing themes. This would make new theme installation very easy.

**Comment by AuditeMarlow** [comment]
Hi Hugo, thanks for showing interest in base16-manager!

I'm going to have to turn down this feature request as there are tools specifically built for this already. I don't feel like it should be base16-manager's responsibility to build new schemes for templates.
