### ISSUE TITLE
LICENSE is always installed globally regardless of the value of PREFIX

### ISSUE THREAD

**Issue by ketsuban** [AuditeMarlow/base16-manager#27]
To fix this, in the Makefile `LICENSEDIR=/usr/share/licenses` should be `LICENSEDIR=${PREFIX}/share/licenses`.

**Comment by AuditeMarlow** [comment]
Not entirely. The `PREFIX` dir is set to `/usr/local` by default. It would make no sense to store licenses in `/usr/local`. What I could do instead is add a new variable that allows you to set the `LICENSEDIR` dynamically.

**Comment by AuditeMarlow** [comment]
Resolved as of fb51f7b.
