### ISSUE TITLE
unlinked config file on theme setting

### ISSUE THREAD

**Issue by aleprovencio** [AuditeMarlow/base16-manager#29]
Hello,
I've noticed some templates such as qutebrowser and dunst when updated by a 'base16-manager set' command will overwrite the config file killing any soft linking it might have, which is a common way to manage dotfiles.

Other templates such as termite and rofi will not damage the links on update, which is the desired behavior.

**Comment by theova** [comment]
Hi!

thanks for this issue. This is indeed a bug!

The broken links are caused by `sed -i command $file` commands.

A possible workaround would be to operate on a temporary file and copy it back after all replacements.

**Comment by AuditeMarlow** [comment]
Fixed as of #32.
