### ISSUE TITLE
Installation via package managers

### ISSUE THREAD

**Issue by chrokh** [AuditeMarlow/base16-manager#3]
As asked in #2 I'm not sure whether platform portability is of interest here but I assume it is since this is a very useful tool. As mentioned in #1 I used to maintain [chrokh/shell-colors](https://github.com/chrokh/shell-colors) 😅  which essentially solves the same problem as this tool does but for macOS users. However I will gladly deprecate that repo in favor of this as this solution is more elegant.

Now to the question 😃 As a Mac user it is super convenient to install shell tools via [Homebrew](https://brew.sh/index_se.html). This script I would argue is an excellent candidate. That would mean that we don't have to handle updates but can simply keep pushing and Homebrew can be used to pull the latest version.

I am not familiar with other package managers like `apt-get` but I assume that publishing a package there is equally trivial?

Is there a rationale behind not making this script installable via package managers or do you mind if I supply a PR that allows users to install this via Homebrew? Apologies if I'm overlooking something fundamental.

**Comment by AuditeMarlow** [comment]
Like I've mentioned in #2 before, I don't have access to MacOS myself, so building a package for Homebrew would... Kind of be up to you, actually.

I'm on Arch Linux myself, and I'll probably end up making an AUR package for this. I'll have to look into other package managers like `apt-get` and the likes, shouldn't be too much of a big deal I guess.

I'll be gladly awaiting your PR. :) Thanks a lot for your input!

**Comment by AuditeMarlow** [comment]
So I've added a `Makefile`, it should be buildable by Linux systems at least. I've created an AUR package, too. Installed it via
```sh
$ yaourt -S base16-manager
```

**Comment by AuditeMarlow** [comment]
Can I still count on you to pick this up, @chrokh?

**Comment by chrokh** [comment]
Sorry about the delay @AuditeMarlow. Swamped with todos as always 😄 See #8
