### ISSUE TITLE
feature request: i3 template

### ISSUE THREAD

**Issue by aleprovencio** [AuditeMarlow/base16-manager#30]
Hello,
It would be very nice having khamer/base16-i3 support since it's the most popular WM nowadays and would make a great combo with the already supported templates.

**Comment by theova** [comment]
Hi there!

Probably it would be cool to implement it with a more generic `set()`. Please see #31.

**Comment by AuditeMarlow** [comment]
You can use base16 schemes in i3 with the Xresources template. Relevant reddit thread: https://www.reddit.com/r/unixporn/comments/4if9xc/i3_you_can_now_use_x_resources_in_i3/

I still think base16-manager should support i3 nonetheless, but it's not required to have base16 colours in i3 right now.

**Comment by aleprovencio** [comment]
@AuditeMarlow sorry I missed that on the enthusiasm of just using base16-manager for the first time. I also don't usually make use of Xresources anymore because it feels deprecated and the solution pointed by @theova is the probably the best.

**Comment by theova** [comment]
@aleprovencio: no worries! It's cool, that you're enthusiastic about using/contributing to base16-manager :-)
