### ISSUE TITLE
Looking for new maintainer(s)

### ISSUE THREAD

**Issue by AuditeMarlow** [AuditeMarlow/base16-manager#54]
I rarely use `base16-manager` myself anymore and frankly I don't want to put up with maintaining something I no longer really use. This is why I'd like to find someone else to take over the project. Otherwise I'll simply archive this repository and tag it as no longer maintained.

**Comment by joshualim92** [comment]
I would hate to see this repo archived. I can at least be an (indefinite) interim maintainer.

**Comment by theova** [comment]
For me, it is pretty much the same. It would be cool, to see the project maintained ad interim by @joshualim92. :+1: 

I can imagine to help out with contributions from time to time.

**Comment by theova** [comment]
What is with the repository in the AUR? I can maintain it, if you don't want to do maintain it by yourself anymore

**Comment by AuditeMarlow** [comment]
In reply to @joshualim92:

> I would hate to see this repo archived. I can at least be an (indefinite) interim maintainer.

Archiving the repository doesn't mean the repository will be gone though. I will keep the source code available to the public. Personally I prefer archiving the repository as this relieves me of the pressure of having to maintain it. Moving ownership of the repository from myself to someone else feels sketchy and I think having someone fork it and maintain it on their own profile feels more in place.



In reply to @theova:

> What is with the repository in the AUR? I can maintain it, if you don't want to do maintain it by yourself anymore

The same philosophy applies to the AUR package as for the repository. I prefer removing my package from the AUR and have someone else create and maintain the package instead.

**Comment by theova** [comment]
> Personally I prefer archiving the repository as this relieves me of the pressure of having to maintain it. Moving ownership of the repository from myself to someone else feels sketchy and I think having someone fork it and maintain it on their own profile feels more in place.

I can absolutely understand your point of view. For the Github-Repo, we could probably move to an organisation repo (@joshualim92 ?).

If you remove the AUR repository, users of it will eventually have troubles during upgrading their system.
So if it is possible to change the ownership, it would be great. Otherwise, please let me know, when your deleting your repo, then I can upload mine after that.

**Comment by joshualim92** [comment]
I'm personally not familiar with how packages in AUR will work but agree with @theova, if it causes some issues with upgrading and versioning, just changing ownership might make more sense.

@theova I think that might be a good idea, move it to an organization repo then the maintainer wouldn't necessarily have to be the repo's owner.

**Comment by AuditeMarlow** [comment]
I can live with moving `base16-manager` to an organisation repo. I'll have a look at how that works and move everything over. I'll have @theova and @joshualim92 added as maintainers.

As for the AUR package, the AUR gives package maintainers to disown packages, which will then be orphaned. AUR users can pick up orphaned packages to start maintaining it themselves. So I guess I am free to disown the AUR package and wait for someone else to pick up its maintenance.

**Comment by AuditeMarlow** [comment]
So I've created a new organisation and just transferred this repo entirely. I wasn't aware that this was even possible, but issues and PRs are intact as they were. :) I've invited @theova and @joshualim92 to the organization as they will be base16-manager's maintainers alongside me and potential newcomers.

As for the AUR package, I've disowned the package and we'll have to see who wants to pick that up.

**Comment by theova** [comment]
Cool, thank you very much!
I've adapted the AUR package :-)

**Comment by joshualim92** [comment]
Thanks @AuditeMarlow! 👍

**Comment by theova** [comment]
We don't have the travis tests activated anymore.

It seems, that I don't have the permissions to modify the settings. @AuditeMarlow: May you change the roles/permissions? (see https://help.github.com/articles/repository-permission-levels-for-an-organization/)

**Comment by theova** [comment]
@kepi Would you like to join us and help improving base16-manager? :smiley:

**Comment by kepi** [comment]
@theova I'm not able to commit enough time and energy in "steady way". But if random spikes of work are ok :) count me in.

**Comment by theova** [comment]
@kepi : cool! You are very welcome to join us :-)


@AuditeMarlow: I'm sorry for pinning, but it would be glad if you could set the appropriate permissions for the maintainers.

> We don't have the travis tests activated anymore.
> 
> It seems, that I don't have the permissions to modify the settings. @AuditeMarlow: May you change the roles/permissions? (see https://help.github.com/articles/repository-permission-levels-for-an-organization/)

**Comment by AuditeMarlow** [comment]
I've created a team within the organisation. I've invited @theova, @joshualim92 and @kepi to join the team. This will grant all of you administrative rights to the repository.

I'll have a look at why Travis won't work anymore.

**Comment by AuditeMarlow** [comment]
I've given Travis access to the repository and updated the badge. View the new builds here: https://travis-ci.org/base16-manager/base16-manager :)

**Comment by theova** [comment]
Cool, thanks :+1:
