### ISSUE TITLE
base16-manager set --silent

### ISSUE THREAD

**Issue by joshualim92** [AuditeMarlow/base16-manager#9]
I was curious what the recommended way is to run
`base16-manager set [theme-name]`

Currently I have it in my .zshrc file but it's echo-ing "Set theme to ..." on every shell generation. Is there a better way to set the theme on shell startup? Or should I make a PR for a `--silent` execution option?

**Comment by AuditeMarlow** [comment]
You shouldn't have to. Once `base16-manager set [theme-name]` is invoked, it should automatically use that theme for every next terminal you open. I strongly discourage adding `base16-manager set [theme-name]` to any auto-startup files.

**Comment by joshualim92** [comment]
Thanks for the quick reply. It appears that I was setting up my environment wrong. I additionally installed chriskempson/base16-shell into my .config dir and that has initialized my shell correctly on startup.

**Comment by AuditeMarlow** [comment]
I've looked into that last problem you're having. base16-shell requires you to have something setup in your bashrc or zshrc. If you change `BASE16_SHELL=$HOME/.config/base16-shell/` to `BASE16_SHELL=$HOME/.base16-manager/chriskempson/base16-shell/`, you will no longer need the seperate base16-shell installation and let base16-manager handle this instead.

**Comment by joshualim92** [comment]
@AuditeMarlow good find! After I looked into the installation instructions for base16-shell I did exactly what you suggested. Thank you!
